version: "3.8"

services:
  mosquitto2:
    build: .
    container_name: mosquitto2
    restart: unless-stopped

    ports:
      - 1883:1883
      - 9001:9001

    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./mosquitto/plugins:/mosquitto/plugins:rw
      - ./mosquitto/log:/mosquitto/log:rw
      - ./mosquitto/data:/mosquitto/data:rw
