name: just a release test

on:
#  push:
#    branches: master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Available platforms
        run: echo ${{ steps.get_version.outputs.VERSION }}

# EOF
